### ISSUE TITLE
module 'cv2.cv2' has no attribute 'xfeatures2d'

### ISSUE THREAD

**Issue by ArchKeyTech** [iago-suarez/beblid-opencv-demo#3]
Hi I would like to know whether the BEBLID descriptor is a non-free algorithm? 
For some reason I am unable to use it in my opencv version 4.5.1 which was installed via pip opencv-contrib.
I get the error " module 'cv2.cv2' has no attribute 'xfeatures2d' " for the line "cv2.xfeatures2d.BEBLID_create()"

**Comment by iago-suarez** [comment]
This is some kind of problem with the opencv-contrib-python installation. You might find this post interesting:

https://stackoverflow.com/questions/37039224/attributeerror-module-object-has-no-attribute-xfeatures2d-python-opencv-2

**Comment by sandeepnmenon** [comment]
+1
Same issue. 
@iago-suarez The post above says to use cv2.SIFT_create and cv2.ORB_create instead of cv2.xfeatures2d.SIFT_create and cv2.xfeatures2d.ORB_create.
However there is no cv2.BEBLID_create.

I am using the latest version: OpenCV Version: 4.5.4-dev

**Comment by iago-suarez** [comment]
Hi, 

Thanks for your interest. BEBLIB is published in Contrib modules, thus you can only use `cv2.xfeatures2d.BEBLID_create`.

In my experience this problem use to appear when you have multiple versions of OpenCV installed in your python environment. For example, opencv-python and opencv-contrib-python. Since opencv-python is already contained in opencv-contrib-python you only need the last one. Try uninstalling both and installing again opencv-contrib-python:

```
pip uninstall opencv-contrib-python
pip uninstall opencv-python
pip install opencv-contrib-python
```

**Comment by chqwer2** [comment]
!pip install "opencv-contrib-python==4.5.1.48" is working for me
